package atomization

import (
	"testing"
)

func metaAtom(id, text string) Atom {
	return Atom{ID: id, Type: AtomMeta, Text: text, ReviewState: ReviewDraft}
}

func ruleAtom(id, text string) Atom {
	return Atom{ID: id, Type: AtomRule, Text: text, ReviewState: ReviewDraft}
}

func atomSet(atoms ...Atom) AtomSet {
	return AtomSet{DocumentRef: "test-doc", SourceFile: "test.md", Atoms: atoms, AtomCount: len(atoms)}
}

// --- Basic extraction ---

func TestExtractGovernanceFromMeta(t *testing.T) {
	as := atomSet(
		metaAtom("m1", "version: 2.1.0\nowner: alice@example.com\nstatus: active\ndomain: insurance\nconfidentiality: restricted"),
		ruleAtom("r1", "La garantie couvre les dégâts des eaux."),
	)
	report := ExtractGovernance(as, GovernanceMetadata{})
	if report.TotalAtoms != 2 {
		t.Fatalf("expected 2 atoms, got %d", report.TotalAtoms)
	}
	// Both atoms should inherit doc-level metadata.
	for _, ca := range report.Atoms {
		if ca.Governance.Version != "2.1.0" {
			t.Fatalf("atom %s: expected version 2.1.0, got %q", ca.Atom.ID, ca.Governance.Version)
		}
		if ca.Governance.Owner != "alice@example.com" {
			t.Fatalf("atom %s: expected owner alice, got %q", ca.Atom.ID, ca.Governance.Owner)
		}
		if ca.Governance.Domain != "insurance" {
			t.Fatalf("atom %s: expected domain insurance, got %q", ca.Atom.ID, ca.Governance.Domain)
		}
		if ca.Governance.Confidentiality != "restricted" {
			t.Fatalf("atom %s: expected restricted, got %q", ca.Atom.ID, ca.Governance.Confidentiality)
		}
	}
}

// --- Defaults applied ---

func TestExtractGovernanceDefaults(t *testing.T) {
	as := atomSet(ruleAtom("r1", "Simple rule."))
	defaults := GovernanceMetadata{
		Version: "1.0", Owner: "bob@test.com", Status: "draft",
		Domain: "testing", Confidentiality: "internal",
	}
	report := ExtractGovernance(as, defaults)
	gov := report.Atoms[0].Governance
	if gov.Version != "1.0" {
		t.Fatalf("expected default version, got %q", gov.Version)
	}
	if gov.Owner != "bob@test.com" {
		t.Fatalf("expected default owner, got %q", gov.Owner)
	}
}

// --- Inline override ---

func TestExtractGovernanceInlineOverride(t *testing.T) {
	as := atomSet(
		metaAtom("m1", "version: 1.0\nstatus: active"),
		ruleAtom("r1", "This rule has status: deprecated inline."),
	)
	report := ExtractGovernance(as, GovernanceMetadata{})
	// r1 should override status to deprecated from inline text.
	r1 := report.Atoms[1]
	if r1.Governance.Status != "deprecated" {
		t.Fatalf("expected inline override to deprecated, got %q", r1.Governance.Status)
	}
}

// --- Atom domain override ---

func TestExtractGovernanceAtomDomainOverride(t *testing.T) {
	atom := ruleAtom("r1", "Rule text.")
	atom.Domain = "finance"
	as := atomSet(atom)
	report := ExtractGovernance(as, GovernanceMetadata{Domain: "insurance"})
	if report.Atoms[0].Governance.Domain != "finance" {
		t.Fatalf("expected atom domain override to finance, got %q", report.Atoms[0].Governance.Domain)
	}
}

// --- Classification: canonical ---

func TestClassifyCanonical(t *testing.T) {
	as := atomSet(ruleAtom("r1", "Active rule content."))
	report := ExtractGovernance(as, GovernanceMetadata{Status: "active"})
	if report.Atoms[0].Class != ClassCanonical {
		t.Fatalf("expected canonical, got %q", report.Atoms[0].Class)
	}
	if report.Canonical != 1 {
		t.Fatalf("expected 1 canonical, got %d", report.Canonical)
	}
}

// --- Classification: generated ---

func TestClassifyGenerated(t *testing.T) {
	cases := []string{
		"This file is auto-generated. Do not edit.",
		"<!-- generated by tool -->",
		"# AUTOGENERATED content",
	}
	for _, text := range cases {
		as := atomSet(ruleAtom("r1", text))
		report := ExtractGovernance(as, GovernanceMetadata{})
		if report.Atoms[0].Class != ClassGenerated {
			t.Fatalf("expected generated for %q, got %q", text, report.Atoms[0].Class)
		}
	}
}

// --- Classification: archive ---

func TestClassifyArchiveByMarker(t *testing.T) {
	as := atomSet(ruleAtom("r1", "This section is archived and obsolete."))
	report := ExtractGovernance(as, GovernanceMetadata{})
	if report.Atoms[0].Class != ClassArchive {
		t.Fatalf("expected archive, got %q", report.Atoms[0].Class)
	}
}

func TestClassifyArchiveByStatus(t *testing.T) {
	as := atomSet(ruleAtom("r1", "Some content."))
	report := ExtractGovernance(as, GovernanceMetadata{Status: "deprecated"})
	if report.Atoms[0].Class != ClassArchive {
		t.Fatalf("expected archive for deprecated status, got %q", report.Atoms[0].Class)
	}
}

func TestClassifyArchiveByReviewState(t *testing.T) {
	atom := ruleAtom("r1", "Rejected content.")
	atom.ReviewState = ReviewRejected
	as := atomSet(atom)
	report := ExtractGovernance(as, GovernanceMetadata{})
	if report.Atoms[0].Class != ClassArchive {
		t.Fatalf("expected archive for rejected, got %q", report.Atoms[0].Class)
	}
}

// --- Missing metadata counts ---

func TestExtractGovernanceMissingCounts(t *testing.T) {
	as := atomSet(ruleAtom("r1", "No metadata at all."))
	report := ExtractGovernance(as, GovernanceMetadata{})
	if report.MissingVersion != 1 {
		t.Fatalf("expected 1 missing version, got %d", report.MissingVersion)
	}
	if report.MissingOwner != 1 {
		t.Fatalf("expected 1 missing owner, got %d", report.MissingOwner)
	}
	if report.MissingStatus != 1 {
		t.Fatalf("expected 1 missing status, got %d", report.MissingStatus)
	}
	if report.MissingDomain != 1 {
		t.Fatalf("expected 1 missing domain, got %d", report.MissingDomain)
	}
}

func TestExtractGovernanceNoMissing(t *testing.T) {
	as := atomSet(metaAtom("m1", "version: 1.0\nowner: a@b.com\nstatus: active\ndomain: test"))
	report := ExtractGovernance(as, GovernanceMetadata{})
	if report.MissingVersion != 0 || report.MissingOwner != 0 || report.MissingStatus != 0 || report.MissingDomain != 0 {
		t.Fatal("expected no missing fields")
	}
}

// --- Empty atom set ---

func TestExtractGovernanceEmpty(t *testing.T) {
	report := ExtractGovernance(AtomSet{}, GovernanceMetadata{})
	if report.TotalAtoms != 0 {
		t.Fatalf("expected 0, got %d", report.TotalAtoms)
	}
}

// --- Mixed classification ---

func TestExtractGovernanceMixed(t *testing.T) {
	as := atomSet(
		metaAtom("m1", "version: 1.0\nstatus: active\nowner: x@y.com\ndomain: test"),
		ruleAtom("r1", "Active canonical rule."),
		ruleAtom("r2", "This is auto-generated content."),
		ruleAtom("r3", "This section is archived."),
	)
	report := ExtractGovernance(as, GovernanceMetadata{})
	if report.Canonical != 2 { // m1 (meta, active) + r1
		t.Fatalf("expected 2 canonical, got %d", report.Canonical)
	}
	if report.Generated != 1 {
		t.Fatalf("expected 1 generated, got %d", report.Generated)
	}
	if report.Archive != 1 {
		t.Fatalf("expected 1 archive, got %d", report.Archive)
	}
}

// --- Regex edge cases ---

func TestExtractVersionFormats(t *testing.T) {
	cases := map[string]string{
		"version: 2.0":      "2.0",
		"Version = '3.1.0'": "3.1.0",
		"v: 4.2":            "4.2",
	}
	for text, expected := range cases {
		as := atomSet(metaAtom("m1", text))
		report := ExtractGovernance(as, GovernanceMetadata{})
		if report.Atoms[0].Governance.Version != expected {
			t.Errorf("for %q: expected version %q, got %q", text, expected, report.Atoms[0].Governance.Version)
		}
	}
}

func TestExtractStatusFormats(t *testing.T) {
	cases := map[string]string{
		"status: active":     "active",
		"Statut = draft":     "draft",
		"status: Deprecated": "deprecated",
	}
	for text, expected := range cases {
		as := atomSet(metaAtom("m1", text))
		report := ExtractGovernance(as, GovernanceMetadata{})
		if report.Atoms[0].Governance.Status != expected {
			t.Errorf("for %q: expected status %q, got %q", text, expected, report.Atoms[0].Governance.Status)
		}
	}
}

// --- ContentClass constants ---

func TestContentClassValues(t *testing.T) {
	if ClassCanonical != "canonical" || ClassGenerated != "generated" ||
		ClassArchive != "archive" || ClassUnknown != "unknown" {
		t.Fatal("content class constants wrong")
	}
}
