package atomization

import (
	"regexp"
	"strings"
)

// ContentClass classifies content provenance.
type ContentClass string

const (
	ClassCanonical ContentClass = "canonical"
	ClassGenerated ContentClass = "generated"
	ClassArchive   ContentClass = "archive"
	ClassUnknown   ContentClass = "unknown"
)

// GovernanceMetadata holds governance fields extracted from atoms.
type GovernanceMetadata struct {
	Version         string `json:"version,omitempty"`
	Owner           string `json:"owner,omitempty"`
	Status          string `json:"status,omitempty"`
	Domain          string `json:"domain,omitempty"`
	Confidentiality string `json:"confidentiality,omitempty"`
}

// ClassifiedAtom pairs an atom with its governance metadata and class.
type ClassifiedAtom struct {
	Atom       Atom               `json:"atom"`
	Governance GovernanceMetadata `json:"governance"`
	Class      ContentClass       `json:"class"`
}

// GovernanceReport summarises the governance extraction result.
type GovernanceReport struct {
	TotalAtoms     int              `json:"total_atoms"`
	Canonical      int              `json:"canonical"`
	Generated      int              `json:"generated"`
	Archive        int              `json:"archive"`
	Unknown        int              `json:"unknown"`
	MissingVersion int              `json:"missing_version"`
	MissingOwner   int              `json:"missing_owner"`
	MissingStatus  int              `json:"missing_status"`
	MissingDomain  int              `json:"missing_domain"`
	Atoms          []ClassifiedAtom `json:"atoms"`
}

var (
	versionRe         = regexp.MustCompile(`(?i)(?:version|v)\s*[:=]\s*["']?([^\s"',]+)`)
	ownerRe           = regexp.MustCompile(`(?i)(?:owner|author|responsable)\s*[:=]\s*["']?([^\s"',]+@[^\s"',]+|[A-Z][a-zA-Z\s]+)`)
	statusRe          = regexp.MustCompile(`(?i)(?:status|statut)\s*[:=]\s*["']?(active|draft|deprecated|archived|abrogated|superseded|pending|effective)`)
	domainRe          = regexp.MustCompile(`(?i)(?:domain|domaine)\s*[:=]\s*["']?([a-z0-9][a-z0-9-]*)`)
	confidentialityRe = regexp.MustCompile(`(?i)(?:confidentiality|confidentialit[eé])\s*[:=]\s*["']?(public|internal|restricted|secret)`)
	generatedMarkers  = []string{"generated", "auto-generated", "do not edit", "autogenerated"}
	archiveMarkers    = []string{"archive", "archived", "obsolete", "deprecated", "abrogated"}
)

// ExtractGovernance processes an AtomSet and returns governance metadata
// and content classification for each atom.
func ExtractGovernance(atomSet AtomSet, defaults GovernanceMetadata) GovernanceReport {
	report := GovernanceReport{
		TotalAtoms: len(atomSet.Atoms),
		Atoms:      make([]ClassifiedAtom, 0, len(atomSet.Atoms)),
	}

	// Collect document-level metadata from meta atoms.
	docMeta := extractDocumentMeta(atomSet.Atoms)
	merged := mergeDefaults(docMeta, defaults)

	for _, atom := range atomSet.Atoms {
		gov := extractAtomGovernance(atom, merged)
		class := classifyContent(atom, gov)

		report.Atoms = append(report.Atoms, ClassifiedAtom{
			Atom:       atom,
			Governance: gov,
			Class:      class,
		})

		switch class {
		case ClassCanonical:
			report.Canonical++
		case ClassGenerated:
			report.Generated++
		case ClassArchive:
			report.Archive++
		default:
			report.Unknown++
		}

		if gov.Version == "" {
			report.MissingVersion++
		}
		if gov.Owner == "" {
			report.MissingOwner++
		}
		if gov.Status == "" {
			report.MissingStatus++
		}
		if gov.Domain == "" {
			report.MissingDomain++
		}
	}

	return report
}

func extractDocumentMeta(atoms []Atom) GovernanceMetadata {
	var meta GovernanceMetadata
	for _, atom := range atoms {
		if atom.Type != AtomMeta {
			continue
		}
		text := atom.Text
		if m := versionRe.FindStringSubmatch(text); len(m) > 1 && meta.Version == "" {
			meta.Version = m[1]
		}
		if m := ownerRe.FindStringSubmatch(text); len(m) > 1 && meta.Owner == "" {
			meta.Owner = strings.TrimSpace(m[1])
		}
		if m := statusRe.FindStringSubmatch(text); len(m) > 1 && meta.Status == "" {
			meta.Status = strings.ToLower(m[1])
		}
		if m := domainRe.FindStringSubmatch(text); len(m) > 1 && meta.Domain == "" {
			meta.Domain = m[1]
		}
		if m := confidentialityRe.FindStringSubmatch(text); len(m) > 1 && meta.Confidentiality == "" {
			meta.Confidentiality = strings.ToLower(m[1])
		}
	}
	return meta
}

func extractAtomGovernance(atom Atom, docMeta GovernanceMetadata) GovernanceMetadata {
	gov := docMeta

	// Override with atom-level domain if set.
	if atom.Domain != "" {
		gov.Domain = atom.Domain
	}

	// Try to extract inline metadata from atom text.
	text := atom.Text
	if m := versionRe.FindStringSubmatch(text); len(m) > 1 {
		gov.Version = m[1]
	}
	if m := statusRe.FindStringSubmatch(text); len(m) > 1 {
		gov.Status = strings.ToLower(m[1])
	}

	return gov
}

func classifyContent(atom Atom, gov GovernanceMetadata) ContentClass {
	lower := strings.ToLower(atom.Text)

	// Check for generated markers.
	for _, marker := range generatedMarkers {
		if strings.Contains(lower, marker) {
			return ClassGenerated
		}
	}

	// Check for archive/deprecated markers.
	for _, marker := range archiveMarkers {
		if strings.Contains(lower, marker) {
			return ClassArchive
		}
	}

	// Status-based classification.
	switch gov.Status {
	case "deprecated", "archived", "abrogated", "superseded":
		return ClassArchive
	case "active", "effective", "draft", "pending":
		return ClassCanonical
	}

	// Review state based.
	switch atom.ReviewState {
	case ReviewApproved, ReviewPending, ReviewDraft:
		return ClassCanonical
	case ReviewRejected:
		return ClassArchive
	}

	// Default: if it has content, it's canonical.
	if strings.TrimSpace(atom.Text) != "" {
		return ClassCanonical
	}

	return ClassUnknown
}

func mergeDefaults(extracted GovernanceMetadata, defaults GovernanceMetadata) GovernanceMetadata {
	result := extracted
	if result.Version == "" {
		result.Version = defaults.Version
	}
	if result.Owner == "" {
		result.Owner = defaults.Owner
	}
	if result.Status == "" {
		result.Status = defaults.Status
	}
	if result.Domain == "" {
		result.Domain = defaults.Domain
	}
	if result.Confidentiality == "" {
		result.Confidentiality = defaults.Confidentiality
	}
	return result
}
