#!/usr/bin/env python3
"""Generate the facet vocabulary artifact from specs/facets.cue.

SEAM-2 (#535). specs/facets.cue is the single source of truth for the CKM facet
controlled vocabularies. This script parses the scalar-axis disjunction
declarations (e.g. ``#FacetTrustTier: "certified" | "indicative" | ...``) out of
that file and emits ``specs/generated/facets-vocab.json``.

Both the bundle validator (scripts/ckm_bundle_validate.py) and external consumers
read the generated JSON, so there is exactly ONE place a value can be added: the
CUE contract. A round-trip test (tests/test_ckm_facets_vocab.py) re-runs this
generator and asserts the committed artifact is byte-identical AND that every
listed value is accepted by ``cue vet`` while a forged value is rejected, so the
artifact cannot silently drift from the CUE source.

Regenerate after changing specs/facets.cue::

    python scripts/ckm_gen_facets_vocab.py
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FACETS_CUE = ROOT / "specs" / "facets.cue"
DEFAULT_OUT = ROOT / "specs" / "generated" / "facets-vocab.json"

# The scalar facet axes whose disjunctions are the bundle-relevant controlled
# vocabularies. Maps the bundle/JSON axis name -> the CUE definition name.
# discipline_role / activity are OPEN term lists (#FacetTermRef, free SKOS refs),
# so they are intentionally NOT enumerated here.
SCALAR_AXES: dict[str, str] = {
    "nature": "#FacetNature",
    "scope_level": "#FacetScopeLevel",
    "trust_tier": "#FacetTrustTier",
    "provenance": "#FacetProvenance",
    "confidentiality": "#FacetConfidentiality",
    "applicability": "#FacetApplicability",
}

_QUOTED = re.compile(r'"([^"]+)"')


def parse_disjunction(cue_text: str, definition: str) -> list[str]:
    """Return the ordered list of string literals in a CUE disjunction definition.

    Parses a block of the form::

        #FacetTrustTier:
            "certified" |
            "indicative" |
            "unverified"

    The block starts at ``<definition>:`` and ends at the first blank line or the
    next top-level ``#Definition:`` declaration.
    """
    anchor = f"\n{definition}:"
    start = cue_text.find(anchor)
    if start == -1:
        raise ValueError(f"definition {definition} not found in facets.cue")
    start += 1  # skip the leading newline
    rest = cue_text[start:]

    # The block body runs until a blank line (double newline) or the next
    # top-level definition. Whichever comes first bounds the disjunction.
    end = len(rest)
    blank = rest.find("\n\n")
    if blank != -1:
        end = min(end, blank)
    next_def = re.search(r"\n#[A-Za-z0-9_]+:", rest)
    if next_def is not None:
        end = min(end, next_def.start())
    block = rest[:end]

    values = _QUOTED.findall(block)
    if not values:
        raise ValueError(f"no string literals parsed for {definition}")
    # Guard against accidental duplicates in the source.
    if len(values) != len(set(values)):
        raise ValueError(f"duplicate values parsed for {definition}: {values}")
    return values


def build_vocab(cue_text: str) -> dict[str, object]:
    axes = {axis: parse_disjunction(cue_text, defn) for axis, defn in SCALAR_AXES.items()}
    return {
        "schema_version": "ckm-facets-vocab-v1",
        "source": "specs/facets.cue",
        "note": (
            "Generated by scripts/ckm_gen_facets_vocab.py from specs/facets.cue "
            "(single source of truth). Do not edit by hand; regenerate after "
            "changing the CUE controlled vocabularies. discipline_role and "
            "activity are open #FacetTermRef lists and are not enumerated."
        ),
        "scalar_axes": axes,
    }


def render(vocab: dict[str, object]) -> str:
    return json.dumps(vocab, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the facet vocabulary artifact from specs/facets.cue.")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="output JSON path (default: specs/generated/facets-vocab.json)")
    parser.add_argument("--check", action="store_true", help="exit non-zero if the committed artifact is stale instead of writing")
    args = parser.parse_args()

    cue_text = FACETS_CUE.read_text(encoding="utf-8")
    vocab = build_vocab(cue_text)
    rendered = render(vocab)

    out_path = Path(args.out)
    if args.check:
        current = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
        if current != rendered:
            print(f"STALE: {out_path} is out of date with specs/facets.cue; run scripts/ckm_gen_facets_vocab.py")
            return 1
        print(f"OK: {out_path} matches specs/facets.cue")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {out_path} ({sum(len(v) for v in vocab['scalar_axes'].values())} values across {len(vocab['scalar_axes'])} axes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
